<a href="https://colab.research.google.com/github/thinkcodegravity/assignment/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #so we can use the np short hand


In [3]:
#create an array (basically a list)
data = np.random.rand(2,3,4)
zeros = np.zeros((2,2,2))
full = np.full((2,2,2),7)
ones = np.ones((2,2,2))

In [14]:
data


array([[[0.92082538, 0.30203459, 0.42350625, 0.31173044],
        [0.60872694, 0.3835505 , 0.3352022 , 0.54129841],
        [0.43483467, 0.17100058, 0.71421267, 0.75991972]],

       [[0.99444724, 0.15981081, 0.95880542, 0.45339381],
        [0.3333393 , 0.67377029, 0.08132477, 0.12934951],
        [0.78967047, 0.27825362, 0.14327686, 0.78422897]]])

In [16]:
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [17]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [18]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [19]:
#create a custom array
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [20]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
type(arr)

numpy.ndarray

In [22]:
#read array
#look at attributes
shape =  data.shape
size = data.size
types = data.dtype

In [24]:
shape

(2, 3, 4)

In [25]:
size

24

In [23]:
types

dtype('float64')

In [26]:
#slicing
arr = data[0]


In [27]:
arr

array([[0.92082538, 0.30203459, 0.42350625, 0.31173044],
       [0.60872694, 0.3835505 , 0.3352022 , 0.54129841],
       [0.43483467, 0.17100058, 0.71421267, 0.75991972]])

In [29]:
slicer = data[0:2]

In [30]:
slicer

array([[[0.92082538, 0.30203459, 0.42350625, 0.31173044],
        [0.60872694, 0.3835505 , 0.3352022 , 0.54129841],
        [0.43483467, 0.17100058, 0.71421267, 0.75991972]],

       [[0.99444724, 0.15981081, 0.95880542, 0.45339381],
        [0.3333393 , 0.67377029, 0.08132477, 0.12934951],
        [0.78967047, 0.27825362, 0.14327686, 0.78422897]]])

In [33]:
reverse = data[-1]

In [34]:
reverse

array([[0.99444724, 0.15981081, 0.95880542, 0.45339381],
       [0.3333393 , 0.67377029, 0.08132477, 0.12934951],
       [0.78967047, 0.27825362, 0.14327686, 0.78422897]])

In [37]:
singlevel = data[0][0][2]

In [38]:
singlevel

np.float64(0.42350624975862006)

In [39]:
#update
#create two lists
list1 = np.random.rand(10)
list2 = np.random.rand(10)


In [40]:
list1

array([0.51673968, 0.43519005, 0.49473487, 0.5835743 , 0.32206621,
       0.48682953, 0.36792418, 0.46680702, 0.81401197, 0.71013861])

In [42]:
list2

array([0.90105298, 0.557834  , 0.74640659, 0.19433801, 0.90892472,
       0.17148776, 0.4475901 , 0.42665979, 0.16462528, 0.4756078 ])

In [46]:
#basic math
add= np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mult = np.multiply(list1,list2)


In [44]:
add

array([1.41779267, 0.99302404, 1.24114146, 0.77791232, 1.23099093,
       0.65831729, 0.81551428, 0.89346681, 0.97863725, 1.18574641])

In [47]:
mult

array([0.46560983, 0.2427638 , 0.36927337, 0.11341067, 0.29273394,
       0.0834853 , 0.16467922, 0.19916779, 0.13400695, 0.33774746])

In [48]:
#stat function (saplem)
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [49]:
maxs

np.float64(0.814011974451467)

In [50]:
data

array([[[0.92082538, 0.30203459, 0.42350625, 0.31173044],
        [0.60872694, 0.3835505 , 0.3352022 , 0.54129841],
        [0.43483467, 0.17100058, 0.71421267, 0.75991972]],

       [[0.99444724, 0.15981081, 0.95880542, 0.45339381],
        [0.3333393 , 0.67377029, 0.08132477, 0.12934951],
        [0.78967047, 0.27825362, 0.14327686, 0.78422897]]])

In [51]:
#assign a new value
data[0][0][0] = 800

In [52]:
data

array([[[8.00000000e+02, 3.02034588e-01, 4.23506250e-01, 3.11730444e-01],
        [6.08726942e-01, 3.83550498e-01, 3.35202197e-01, 5.41298405e-01],
        [4.34834667e-01, 1.71000575e-01, 7.14212670e-01, 7.59919720e-01]],

       [[9.94447244e-01, 1.59810807e-01, 9.58805416e-01, 4.53393814e-01],
        [3.33339296e-01, 6.73770293e-01, 8.13247667e-02, 1.29349510e-01],
        [7.89670472e-01, 2.78253621e-01, 1.43276859e-01, 7.84228973e-01]]])

In [53]:
#sort an array
data.sort()

In [54]:
data

array([[[3.02034588e-01, 3.11730444e-01, 4.23506250e-01, 8.00000000e+02],
        [3.35202197e-01, 3.83550498e-01, 5.41298405e-01, 6.08726942e-01],
        [1.71000575e-01, 4.34834667e-01, 7.14212670e-01, 7.59919720e-01]],

       [[1.59810807e-01, 4.53393814e-01, 9.58805416e-01, 9.94447244e-01],
        [8.13247667e-02, 1.29349510e-01, 3.33339296e-01, 6.73770293e-01],
        [1.43276859e-01, 2.78253621e-01, 7.84228973e-01, 7.89670472e-01]]])

In [67]:
#data.sort(reverse=True) # This causes a TypeError
data = np.sort(data, axis=-1)[:, :, ::-1]

In [68]:
data

array([[[8.00000000e+02, 4.23506250e-01, 3.83550498e-01, 3.35202197e-01,
         3.11730444e-01, 3.02034588e-01],
        [7.59919720e-01, 7.14212670e-01, 6.08726942e-01, 5.41298405e-01,
         4.34834667e-01, 1.71000575e-01]],

       [[9.94447244e-01, 9.58805416e-01, 4.53393814e-01, 1.59810807e-01,
         1.29349510e-01, 8.13247667e-02],
        [7.89670472e-01, 7.84228973e-01, 6.73770293e-01, 3.33339296e-01,
         2.78253621e-01, 1.43276859e-01]]])

In [69]:
opp = np.sort(data)
opp[::-1]
print(opp)

[[[3.02034588e-01 3.11730444e-01 3.35202197e-01 3.83550498e-01
   4.23506250e-01 8.00000000e+02]
  [1.71000575e-01 4.34834667e-01 5.41298405e-01 6.08726942e-01
   7.14212670e-01 7.59919720e-01]]

 [[8.13247667e-02 1.29349510e-01 1.59810807e-01 4.53393814e-01
   9.58805416e-01 9.94447244e-01]
  [1.43276859e-01 2.78253621e-01 3.33339296e-01 6.73770293e-01
   7.84228973e-01 7.89670472e-01]]]


In [55]:
data = data.reshape((2,2,-1))

In [56]:
data

array([[[3.02034588e-01, 3.11730444e-01, 4.23506250e-01, 8.00000000e+02,
         3.35202197e-01, 3.83550498e-01],
        [5.41298405e-01, 6.08726942e-01, 1.71000575e-01, 4.34834667e-01,
         7.14212670e-01, 7.59919720e-01]],

       [[1.59810807e-01, 4.53393814e-01, 9.58805416e-01, 9.94447244e-01,
         8.13247667e-02, 1.29349510e-01],
        [3.33339296e-01, 6.73770293e-01, 1.43276859e-01, 2.78253621e-01,
         7.84228973e-01, 7.89670472e-01]]])

In [57]:
#append
zeros = np.zeros((8))
print(zeros)
zeros = np.append(zeros,[3,4])
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [58]:
zeros = np.insert(zeros,2,8)
print(zeros)

[0. 0. 8. 0. 0. 0. 0. 0. 0. 3. 4.]


In [59]:
#delete
data

array([[[3.02034588e-01, 3.11730444e-01, 4.23506250e-01, 8.00000000e+02,
         3.35202197e-01, 3.83550498e-01],
        [5.41298405e-01, 6.08726942e-01, 1.71000575e-01, 4.34834667e-01,
         7.14212670e-01, 7.59919720e-01]],

       [[1.59810807e-01, 4.53393814e-01, 9.58805416e-01, 9.94447244e-01,
         8.13247667e-02, 1.29349510e-01],
        [3.33339296e-01, 6.73770293e-01, 1.43276859e-01, 2.78253621e-01,
         7.84228973e-01, 7.89670472e-01]]])

In [60]:
np.delete(data,0,axis=1)

array([[[0.54129841, 0.60872694, 0.17100058, 0.43483467, 0.71421267,
         0.75991972]],

       [[0.3333393 , 0.67377029, 0.14327686, 0.27825362, 0.78422897,
         0.78967047]]])

In [61]:
#save an array
np.save('new_array',data)

In [62]:
test = np.load('new_array.npy')

In [63]:
test

array([[[3.02034588e-01, 3.11730444e-01, 4.23506250e-01, 8.00000000e+02,
         3.35202197e-01, 3.83550498e-01],
        [5.41298405e-01, 6.08726942e-01, 1.71000575e-01, 4.34834667e-01,
         7.14212670e-01, 7.59919720e-01]],

       [[1.59810807e-01, 4.53393814e-01, 9.58805416e-01, 9.94447244e-01,
         8.13247667e-02, 1.29349510e-01],
        [3.33339296e-01, 6.73770293e-01, 1.43276859e-01, 2.78253621e-01,
         7.84228973e-01, 7.89670472e-01]]])